#!/bin/bash


time=$(date "+%Y-%m-%d %H:%M:%S")
#time='2020-01-17 17:41:54'


for i in $(docker ps|awk '{print $NF}' );
do
    if [[ $i == docker* ]];then
        echo $i time is "$(docker exec -it $i date )"
        docker cp /etc/localtime $i:/etc/
        docker exec -it $i date -s "$time"
        docker restart $i
        echo " $i time after modify is $(docker exec -it $i date )"
    fi
done

