version: '2'
services:
  csp:
    image: registry.bocloud.com.cn/cmp/bocloud.csp:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/csp.properties:/BeyondCMP/config/csp.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - prometheus:prometheus
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18080:18080/tcp
    labels:
      io.rancher.container.pull_image: always
  css:
    image: registry.bocloud.com.cn/cmp/bocloud.css:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/css.properties:/BeyondCMP/config/css.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18095:18095/tcp
    labels:
      io.rancher.container.pull_image: always
  zookeeper:
    image: zookeeper:3.5.5
    environment:
      ZOO_TICK_TIME: '2000'
      ZOO_INIT_LIMIT: '10'
      ZOO_SYNC_LIMIT: '5'
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: '3'
      ZOO_AUTOPURGE_PURGEINTERVAL: '1'
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf
      TZ: Asia/Shanghai
    stdin_open: true
    volumes:
    - /home/cmp/data/zookeeper/data/:/data/
    - /home/cmp/data/zookeeper/datalog/:/datalog/
    - /home/cmp/data/zookeeper/logs/:/logs/
    tty: true
    ports:
    - 2181:2181/tcp
    labels:
      io.rancher.container.pull_image: always
  cop:
    image: registry.bocloud.com.cn/cmp/bocloud.cop:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/cop.properties:/BeyondCMP/config/cop.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18090:18090/tcp
    labels:
      io.rancher.container.pull_image: always
  soc:
    image: registry.bocloud.com.cn/cmp/bocloud.soc:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/soc.properties:/BeyondCMP/config/soc.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18088:18088/tcp
    labels:
      io.rancher.container.pull_image: always
  cmdb:
    image: registry.bocloud.com.cn/cmp/bocloud.cmdb:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/cmdb.properties:/BeyondCMP/config/cmdb.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18082:18082/tcp
    labels:
      io.rancher.container.pull_image: always
  cos:
    image: registry.bocloud.com.cn/cmp/bocloud.cos:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/cos.properties:/BeyondCMP/config/cos.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18096:18096/tcp
    labels:
      io.rancher.container.pull_image: always
  cmp:
    image: registry.bocloud.com.cn/cmp/bocloud.cmp:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/cmp.properties:/BeyondCMP/config/cmp.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18081:18081/tcp
    labels:
      io.rancher.container.pull_image: always
  blackbox-exporter:
    image: carlosedp/blackbox_exporter:v0.13.0
    stdin_open: true
    volumes:
    - /home/cmp/:/home/cmp/
    - /etc/localtime:/etc/localtime
    tty: true
    ports:
    - 9115:9115/tcp
  rabbitmq:
    image: rabbitmq:3.6.5-management
    environment:
      RABBITMQ_DEFAULT_PASS: bocloud
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_VHOST: cmp
      TZ: Asia/Shanghai
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
  pontus:
    image: registry.bocloud.com.cn/cmp/bocloud.pontus:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/pontus/config.yml:/opt/pontus/pontus/config.yml
    - /home/cmp/logs/worker/:/var/log/bocloud/
    tty: true
    links:
    - zookeeper:zookeeper
    ports:
    - 18097:18097/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.requested_ip: 10.42.1.11
  redis:
    image: redis:3.2.12
    environment:
      TZ: Asia/Shanghai
    stdin_open: true
    volumes:
    - /home/cmp/config/redis/redis.conf:/etc/redis.conf
    - /home/cmp/data/redis/:/data/
    tty: true
    ports:
    - 5379:5379/tcp
    command:
    - redis-server
    - /etc/redis.conf
    - --loglevel
    - verbose
    - --appendonly
    - 'yes'
    labels:
      io.rancher.container.pull_image: always
  node-exporter:
    image: prom/node-exporter:v0.18.1
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    tty: true
    ports:
    - 9100:9100/tcp
    labels:
      io.rancher.container.pull_image: always
  telegraf:
    image: telegraf:1.12.1
    stdin_open: true
    volumes:
    - /home/cmp/telegraf/telegraf.d/:/etc/telegraf/telegraf.d/
    - /home/cmp/config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    - /etc/localtime:/etc/localtime
    tty: true
    ports:
    - 9273:9273/tcp
    command:
    - -config
    - /etc/telegraf/telegraf.conf
    - -config-directory
    - /etc/telegraf/telegraf.d
    labels:
      io.rancher.container.pull_image: always
  csc:
    image: registry.bocloud.com.cn/cmp/bocloud.csc:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/csc.properties:/BeyondCMP/config/csc.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18092:18092/tcp
    labels:
      io.rancher.container.pull_image: always
  exporter:
    image: registry.bocloud.com.cn/cmp/bocloud.exporter:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/exporter.properties:/BeyondCMP/config/exporter.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18094:18094/tcp
    labels:
      io.rancher.container.pull_image: always
  web:
    image: registry.bocloud.com.cn/cmp/bocloud.web:4.3.0-RELEASE
    environment:
      TZ: Asia/Shanghai
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/web/nginx.conf:/etc/nginx/nginx.conf
    - /home/cmp/logs/nginx/:/var/log/nginx/
    tty: true
    links:
    - csc:csc
    - cmc:cmc
    ports:
    - 60006:60006/tcp
    - 60008:60008/tcp
    labels:
      io.rancher.container.pull_image: always
  cmc:
    image: registry.bocloud.com.cn/cmp/bocloud.cmc:4.3.0-RELEASE
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/services/cmc.properties:/BeyondCMP/config/cmc.properties
    - /home/cmp/logs/:/root/cmp/logs/
    tty: true
    links:
    - redis:redis
    - zookeeper:zookeeper
    - mysql:mysql
    - rabbitmq:rabbitmq
    ports:
    - 18091:18091/tcp
    labels:
      io.rancher.container.pull_image: always
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: Cmp@v587
      MYSQL_DATABASE: cmp
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    stdin_open: true
    volumes:
    - /home/cmp/data/mysql/:/var/lib/mysql
    - /home/cmp/config/mysql/:/etc/mysql/conf.d
    - /home/cmp/mysql/init/:/docker-entrypoint-initdb.d
    tty: true
    ports:
    - 3306:3306/tcp
    command:
    - --default-authentication-plugin=mysql_native_password
    labels:
      io.rancher.container.pull_image: always
  prometheus:
    image: prom/prometheus:v2.14.0
    stdin_open: true
    volumes:
    - /home/cmp/:/home/cmp/
    - /home/cmp/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - /etc/localtime:/etc/localtime
    tty: true
    links:
    - blackbox-exporter:blackbox-exporter
    - telegraf:telegraf
    - alertmanager:alertmanager
    ports:
    - 19091:19091/tcp
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.listen-address=0.0.0.0:19091
    - --web.enable-lifecycle
    - --storage.tsdb.retention=45d
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    labels:
      io.rancher.container.pull_image: always
  worker:
    image: registry.bocloud.com.cn/cmp/bocloud.worker:4.3.0-RELEASE
    environment:
      TZ: Asia/Shanghai
    stdin_open: true
    volumes:
    - /home/cmp:/home/cmp/
    - /home/cmp/config/worker/bocloud_worker_config.yml:/opt/worker/bocloud_worker/bocloud_worker_config.yml
    - /home/cmp/logs/worker/:/var/log/bocloud/
    tty: true
    links:
    - zookeeper:zookeeper
    - rabbitmq:rabbitmq
    ports:
    - 18089:18089/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.requested_ip: 10.42.1.10
  alertmanager:
    image: prom/alertmanager:v0.16.1
    stdin_open: true
    volumes:
    - /home/cmp/config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    - /etc/localtime:/etc/localtime
    tty: true
    ports:
    - 9093:9093/tcp
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    - --cluster.listen-address=
    labels:
      io.rancher.container.pull_image: always
